name: ayurvanta
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  pin_code_fields: ^8.0.1
  lottie: ^3.0.0
  animate_do: ^3.3.4
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.1.0
  permission_handler: ^11.3.0
  provider: ^6.1.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  image_picker: ^1.0.7
  razorpay_flutter: ^1.3.6
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  avatar_glow: ^3.0.0
  url_launcher: ^6.3.2
  flutter_local_notifications: ^17.2.2
  audioplayers: ^6.0.0
  timezone: ^0.9.4
  sensors_plus: ^4.0.2
  flutter_blue_plus: ^1.31.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
